### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by mweibel** [jsturtevant/windows-debug#19]
```
$ kubectl krew install windows-debug
Updated the local copy of plugin index.
Installing plugin: windows-debug
W1201 08:56:08.545576   36364 install.go:164] failed to install plugin "windows-debug": plugin "windows-debug" does not offer installation for this platform
failed to install some plugins: [windows-debug]: plugin "windows-debug" does not offer installation for this platform
```

Would be great to add macOS support. As far as I can see this is only a bash script so might be just adding darwin arm64 and amd64 to some supported platform list? 
Thanks for the plugin, looking forward to trying it! :)

**Comment by mweibel** [comment]
added a PR to remove the arch from darwin. I'm not quite sure if that is all it needs. Didn't write krew plugins yet :)

**Comment by jsturtevant** [comment]
Thanks!  https://github.com/kubernetes-sigs/krew-index/pull/2828/ will need to be merged then it should be avaliable!
